# Generated by Django 6.0.2 on 2026-03-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='value',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(blank=True, null=True, verbose_name='湿度'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='pm25',
            field=models.IntegerField(blank=True, null=True, verbose_name='PM2.5数值'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='smoke',
            field=models.IntegerField(blank=True, null=True, verbose_name='烟雾浓度'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='status',
            field=models.CharField(default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='温度'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上报时间'),
        ),
    ]
